apiVersion: apps/v1
kind: Deployment
metadata:
  name: rs-app
  labels:
    app: rs-app
spec:
  selector:
    matchLabels:
      app: rs-app
  template:
    metadata:
      labels:
        app: rs-app
    spec:
      containers:
      - name: rs-app
        image: rs-app:local
        imagePullPolicy: Never
        ports:
        - containerPort: 8080